/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cajero.vista;

import cajero.bd.CuentaDAO;
import cajero.modelo.Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ymala
 */
public class PantallaRetiro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaRetiro.class.getName());

    /**
     * Creates new form PantallaRetiro
     */
    private Usuario usuarioSesion;
    
    public PantallaRetiro(Usuario user) {
        initComponents();
        this.setSize(709, 451);
        this.pack();
        lblError.setVisible(false);
        this.usuarioSesion = user;

        
        txtMonto.setForeground(Color.GRAY);
        txtMonto.setText(" $0.00");

        txtMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtMonto.getText().equals(" $0.00")) {
                    txtMonto.setText("");
                    txtMonto.setForeground(Color.BLACK);
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtMonto.getText().isEmpty()) {
                    txtMonto.setForeground(Color.GRAY);
                    txtMonto.setText(" $0.00");
                }
            }
        });
        
        mostrarSaldo(); // Llamamos a la función para mostrar el dinero
        
        
    }
    
    private void mostrarSaldo() {
        CuentaDAO dao = new CuentaDAO();
        double saldo = dao.obtenerSaldo(usuarioSesion.getId());

        // Formateamos el texto para que se vea profesional
        lblSaldoDisponible.setText("Saldo disponible: $ " + String.format("%.2f", saldo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblSaldoDisponible = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cajero Automático");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(5, 31, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 182, 155), 3, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(11, 43, 38));
        lblTitulo.setText("Retiro");
        jPanel2.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        lblMonto.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(0, 0, 0));
        lblMonto.setText("Monto a retirar");
        jPanel2.add(lblMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtMonto.setBackground(new java.awt.Color(204, 204, 204));
        txtMonto.setForeground(new java.awt.Color(153, 153, 153));
        txtMonto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 182, 155), 1, true));
        jPanel2.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 250, 40));

        lblError.setForeground(new java.awt.Color(51, 0, 0));
        jPanel2.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 260, 240, -1));

        btnConfirmar.setBackground(new java.awt.Color(142, 182, 155));
        btnConfirmar.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(11, 43, 38));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);
        jPanel2.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 100, 40));

        btnCancelar.setBackground(new java.awt.Color(179, 179, 179));
        btnCancelar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(43, 43, 43));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 90, 40));

        lblSaldoDisponible.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblSaldoDisponible.setForeground(new java.awt.Color(22, 56, 50));
        lblSaldoDisponible.setText("Saldo disponible: [Monto]");
        jPanel2.add(lblSaldoDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajeroautomatico/imagenes/retiro grande.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 300, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Volver al menú principal
        MenuPrincipal menu = new MenuPrincipal(usuarioSesion);
        menu.setVisible(true);

        // Cerrar la pantalla de retiro
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            // 1. Primero obtenemos el monto del texto
            double monto = Double.parseDouble(txtMonto.getText());

            // 2. Validamos que sea un monto lógico
            if (monto <= 0) {
                JOptionPane.showMessageDialog(this, "Ingrese un monto válido.");
                return;
            }

            // 3. AHORA SÍ, abrimos la confirmación con los datos listos
            // Pasamos: tipo ("retiro"), el usuario y el monto capturado
            PantallaConfirmacion confirmacion = new PantallaConfirmacion("retiro", usuarioSesion, monto);
            confirmacion.setVisible(true);

            // 4. Cerramos esta pantalla
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido.");
        }
        
        // Cerrar la pantalla de retiro
        this.dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblSaldoDisponible;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
