
package cajero.vista;

import cajero.bd.UsuarioDAO;
import cajero.modelo.Cuenta;
import cajero.modelo.Operacion;
import cajero.modelo.Transferencia;
import cajero.modelo.Usuario;
import cajero.servicio.CorreoService;
import java.text.SimpleDateFormat;
import java.util.Date;


public class PantallaConfirmacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaConfirmacion.class.getName());
    private Usuario usuarioSesion;
    private Operacion operacion;
   

    /**
     * Creates new form PantallaConfirmacion
     */
    public PantallaConfirmacion(Operacion operacion, Usuario user, double saldoActual) {
        initComponents();
        this.setSize(709, 451);
        this.pack();
        this.usuarioSesion = user;
        this.operacion = operacion;
        setLocationRelativeTo(null);   
        
        // Si la operación es transferencia, mostrar cuenta destino y titular
        if (operacion instanceof Transferencia) {
            Transferencia transferencia = (Transferencia) operacion;
            Cuenta cuentaDestino = transferencia.getCuentaDestino();

            lblCuentaDestino.setVisible(true);
            lblValorCuentaDestino.setVisible(true);
            lblTitular.setVisible(true);
            lblValorTitular.setVisible(true);

            lblValorCuentaDestino.setText(cuentaDestino.getNumeroCuenta());

            UsuarioDAO usuarioDAO = new UsuarioDAO();
            Usuario titular = usuarioDAO.obtenerUsuarioPorId(cuentaDestino.getIdUsuario());
            lblValorTitular.setText(titular.getNombre());
        } else {
            // Ocultar campos si no es transferencia
            lblCuentaDestino.setVisible(false);
            lblValorCuentaDestino.setVisible(false);
            lblTitular.setVisible(false);
            lblValorTitular.setVisible(false);
        }
        
        
        // Mostrar los datos reales en los labels
        lblValorTipoOperacion.setText(operacion.getTipo());
        lblValorMonto.setText("$" + operacion.getMonto());
        
        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy (HH:mm:ss)");
        String fechaFormateada = formato.format(fecha);
        
        lblValorFecha.setText(fechaFormateada);
        lblValorSaldo.setText(String.format("$ %.2f", saldoActual));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnSi = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        lblIcono = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblResumen = new javax.swing.JLabel();
        lblTipoOperacion = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        lblCuentaDestino = new javax.swing.JLabel();
        lblValorCuentaDestino = new javax.swing.JLabel();
        lblTitular = new javax.swing.JLabel();
        lblValorTitular = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblValorTipoOperacion = new javax.swing.JLabel();
        lblSaldoActual = new javax.swing.JLabel();
        lblValorMonto = new javax.swing.JLabel();
        lblValorFecha = new javax.swing.JLabel();
        lblValorSaldo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPregunta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cajero Automatico");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(5, 31, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 182, 155), 3, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(11, 43, 38));
        lblTitulo.setText("¡Operación realizada con éxito!");
        jPanel2.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        btnSi.setBackground(new java.awt.Color(142, 182, 155));
        btnSi.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        btnSi.setForeground(new java.awt.Color(11, 43, 38));
        btnSi.setText("Si, enviar al correo");
        btnSi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSiFocusGained(evt);
            }
        });
        btnSi.addActionListener(this::btnSiActionPerformed);
        jPanel2.add(btnSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 140, 30));

        btnNo.setBackground(new java.awt.Color(179, 179, 179));
        btnNo.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnNo.setForeground(new java.awt.Color(43, 43, 43));
        btnNo.setText("No, gracias");
        btnNo.addActionListener(this::btnNoActionPerformed);
        jPanel2.add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, -1));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajeroautomatico/imagenes/check (1).png"))); // NOI18N
        jPanel2.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jPanel3.setBackground(new java.awt.Color(218, 241, 222));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 56, 50), 2, true));

        lblResumen.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblResumen.setForeground(new java.awt.Color(0, 0, 0));
        lblResumen.setText("Resumen de la operación:");

        lblTipoOperacion.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblTipoOperacion.setForeground(new java.awt.Color(22, 56, 50));
        lblTipoOperacion.setText("Tipo de operación:");

        lblMonto.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(22, 56, 50));
        lblMonto.setText("Monto:");

        lblCuentaDestino.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblCuentaDestino.setForeground(new java.awt.Color(22, 56, 50));
        lblCuentaDestino.setText("Cuenta destino:");

        lblValorCuentaDestino.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lblValorCuentaDestino.setForeground(new java.awt.Color(22, 56, 50));
        lblValorCuentaDestino.setText("[cuenta]");

        lblTitular.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblTitular.setForeground(new java.awt.Color(22, 56, 50));
        lblTitular.setText("Titular:");

        lblValorTitular.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lblValorTitular.setForeground(new java.awt.Color(22, 56, 50));
        lblValorTitular.setText("[titular]");

        lblFecha.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(22, 56, 50));
        lblFecha.setText("Fecha y hora:");

        lblValorTipoOperacion.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lblValorTipoOperacion.setForeground(new java.awt.Color(22, 56, 50));
        lblValorTipoOperacion.setText("[Operacion]");

        lblSaldoActual.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblSaldoActual.setForeground(new java.awt.Color(22, 56, 50));
        lblSaldoActual.setText("Saldo actual:");

        lblValorMonto.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lblValorMonto.setForeground(new java.awt.Color(22, 56, 50));
        lblValorMonto.setText("[Monto]");

        lblValorFecha.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lblValorFecha.setForeground(new java.awt.Color(22, 56, 50));
        lblValorFecha.setText("[fecha]");

        lblValorSaldo.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lblValorSaldo.setForeground(new java.awt.Color(22, 56, 50));
        lblValorSaldo.setText("[saldo]");

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResumen)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblSaldoActual)
                                .addGap(53, 53, 53)
                                .addComponent(lblValorSaldo)))
                        .addGap(50, 91, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoOperacion)
                                    .addComponent(lblMonto)
                                    .addComponent(lblCuentaDestino)
                                    .addComponent(lblTitular)
                                    .addComponent(lblFecha))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorTipoOperacion)
                                    .addComponent(lblValorMonto)
                                    .addComponent(lblValorTitular)
                                    .addComponent(lblValorFecha)
                                    .addComponent(lblValorCuentaDestino))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResumen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTipoOperacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMonto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCuentaDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFecha)
                            .addComponent(lblValorFecha))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblValorTipoOperacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorMonto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorCuentaDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorTitular)
                        .addGap(41, 41, 41)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldoActual)
                    .addComponent(lblValorSaldo))
                .addGap(9, 9, 9))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 260, 200));

        lblPregunta.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblPregunta.setForeground(new java.awt.Color(11, 43, 38));
        lblPregunta.setText("¿Desea recibir su comprobante?");
        jPanel2.add(lblPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 300, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        // Abrir la pantalla de cierre
        PantallaCierre cierre = new PantallaCierre();
        cierre.setVisible(true);

        // Cerrar la pantalla actual de confirmación
        this.dispose();
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        
        // Crear el servicio de correo
        CorreoService correoService = new CorreoService();
    
        boolean enviado = correoService.enviarComprobante(usuarioSesion, operacion);
        System.out.println(enviado 
            ? "Comprobante enviado a su correo." 
            : "Error al enviar el comprobante.");

        // Abrir la pantalla de cierre
        PantallaComprobante comprobante = new PantallaComprobante(usuarioSesion);
        comprobante.setVisible(true);
        
        // Cerrar la pantalla actual de confirmación
        this.dispose();
    }//GEN-LAST:event_btnSiActionPerformed

    private void btnSiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSiFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiFocusGained

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnSi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCuentaDestino;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JLabel lblSaldoActual;
    private javax.swing.JLabel lblTipoOperacion;
    private javax.swing.JLabel lblTitular;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorCuentaDestino;
    private javax.swing.JLabel lblValorFecha;
    private javax.swing.JLabel lblValorMonto;
    private javax.swing.JLabel lblValorSaldo;
    private javax.swing.JLabel lblValorTipoOperacion;
    private javax.swing.JLabel lblValorTitular;
    // End of variables declaration//GEN-END:variables
}
