
package cajero.vista;

import cajero.modelo.Usuario;
import cajero.servicio.AuthService;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author YMALAI DORANGEL LEONARDO RAMON
 */
public class PantallaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaLogin.class.getName());

    /**
     * Creates new form PantallaLogin
     */
    public PantallaLogin() {
        initComponents();
        lblError.setVisible(false);
        this.setSize(709, 451);
        this.pack();
        
        txtCuenta.setForeground(Color.GRAY);
        txtCuenta.setText(" Ingresa tu número de cuenta");

        txtCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtCuenta.getText().equals(" Ingresa tu número de cuenta")) {
                txtCuenta.setText("");
                txtCuenta.setForeground(Color.BLACK);
            }
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtCuenta.getText().isEmpty()) {
                txtCuenta.setForeground(Color.GRAY);
                txtCuenta.setText(" Ingresa tu número de cuenta");
            }
        }
   
        });
        
        txtPin.setEchoChar((char)0);
        txtPin.setForeground(Color.GRAY);
        txtPin.setText(" Ingresa tu PIN");

        txtPin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (String.valueOf(txtPin.getPassword()).equals(" Ingresa tu PIN")) {
                    txtPin.setText("");
                    txtPin.setForeground(Color.BLACK);
                    txtPin.setEchoChar('•');
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtPin.getPassword().length == 0) {
                    txtPin.setEchoChar((char)0);
                    txtPin.setForeground(Color.GRAY);
                    txtPin.setText(" Ingresa tu PIN");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCentro = new javax.swing.JPanel();
        lblBanco = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblCuenta = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        lblPin = new javax.swing.JLabel();
        txtPin = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cajero Automático");
        setBackground(new java.awt.Color(51, 153, 0));
        setBounds(new java.awt.Rectangle(0, 0, 950, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(5, 31, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCentro.setBackground(new java.awt.Color(255, 255, 255));
        panelCentro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 182, 155), 3, true));
        panelCentro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBanco.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblBanco.setForeground(new java.awt.Color(5, 31, 32));
        lblBanco.setText("Banco Digital");
        panelCentro.add(lblBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        lblSubtitulo.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblSubtitulo.setText("Bienvenido a tu cajero virtual");
        panelCentro.add(lblSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        lblCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCuenta.setForeground(new java.awt.Color(0, 0, 0));
        lblCuenta.setText("Número de cuenta");
        panelCentro.add(lblCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtCuenta.setBackground(new java.awt.Color(204, 204, 204));
        txtCuenta.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txtCuenta.setForeground(new java.awt.Color(153, 153, 153));
        txtCuenta.setToolTipText("Ingrese sus 8 dígitos");
        txtCuenta.setAlignmentX(0.0F);
        txtCuenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 182, 155), 1, true));
        txtCuenta.addActionListener(this::txtCuentaActionPerformed);
        panelCentro.add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 210, 30));

        lblPin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPin.setForeground(new java.awt.Color(0, 0, 0));
        lblPin.setText("PIN");
        panelCentro.add(lblPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtPin.setBackground(new java.awt.Color(204, 204, 204));
        txtPin.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txtPin.setForeground(new java.awt.Color(153, 153, 153));
        txtPin.setToolTipText("Ingrese su PIN");
        txtPin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 182, 155), 1, true));
        txtPin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPinKeyTyped(evt);
            }
        });
        panelCentro.add(txtPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, 30));

        btnIngresar.setBackground(new java.awt.Color(22, 56, 50));
        btnIngresar.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(this::btnIngresarActionPerformed);
        panelCentro.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        lblError.setForeground(new java.awt.Color(149, 18, 44));
        panelCentro.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        icono.setBackground(new java.awt.Color(11, 43, 38));
        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajeroautomatico/imagenes/office-building.png"))); // NOI18N
        panelCentro.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 70, -1));

        jPanel1.add(panelCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 250, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        String cuenta = txtCuenta.getText();
        String pin = new String(txtPin.getPassword()); // Para JPasswordField

        // REGLA DE ORO: Validar los 8 dígitos
        // "\\d{8}" significa: solo números y que sean exactamente 8
        if (!cuenta.matches("\\d{8}")) {
            JOptionPane.showMessageDialog(this, 
                "El número de cuenta debe tener exactamente 8 dígitos numéricos.", 
                "Error de formato", 
                JOptionPane.WARNING_MESSAGE);
            return; // Detenemos el proceso aquí mismo
        }
        
        // Validar PIN (Exactamente 4 dígitos)
        // El regex "\\d{4}" obliga a que sean solo números y solo cuatro
        if (!pin.matches("\\d{4}")) {
            JOptionPane.showMessageDialog(this, "El PIN debe ser de exactamente 4 dígitos.");
            return;
        }
        
        AuthService auth = new AuthService();
        Usuario user = auth.login(cuenta, pin);

        if (user != null) {
            // SI EL LOGIN ES EXITOSO:
            MenuPrincipal menu = new MenuPrincipal(user); // Pasamos el usuario a la siguiente pantalla
            menu.setVisible(true);
            this.dispose(); // Cerramos el login
        } else {
            // SI FALLA:
            int intentos = auth.getIntentosRestantes();
            if (intentos == 0) {
                new PantallaBloqueada().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Datos incorrectos. Intentos restantes: " + intentos);
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtPinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPinKeyTyped
        // Si ya hay 4 caracteres o si lo que presiona no es un número, lo ignora
        if (txtPin.getPassword().length >= 4 || !Character.isDigit(evt.getKeyChar())) {
            evt.consume(); 
        }
    }//GEN-LAST:event_txtPinKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel icono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblPin;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JPasswordField txtPin;
    // End of variables declaration//GEN-END:variables
}
