/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cajero.vista;

/**
 *
 * @author ymala
 */
public class PantallaComprobante extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaComprobante.class.getName());

    /**
     * Creates new form PantallaComprobante
     */
    public PantallaComprobante() {
        initComponents();
        this.setSize(709, 451);
        this.pack();
        
        lblCorreo.setText("juan.perez@email.com");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        lblIcono = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblMensaje = new javax.swing.JLabel();
        lblMensaje1 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cajero Automatico");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(5, 31, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 182, 155), 3, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(11, 43, 38));
        lblTitulo.setText("¡Comprobante enviado a tu correo!");
        jPanel2.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 280, -1));

        btnMenu.setBackground(new java.awt.Color(142, 182, 155));
        btnMenu.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(11, 43, 38));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajeroautomatico/imagenes/flecha.png"))); // NOI18N
        btnMenu.setText(" Volver al menú");
        btnMenu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnMenuFocusGained(evt);
            }
        });
        btnMenu.addActionListener(this::btnMenuActionPerformed);
        jPanel2.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 140, 30));

        btnFinalizar.setBackground(new java.awt.Color(179, 179, 179));
        btnFinalizar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(43, 43, 43));
        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajeroautomatico/imagenes/cerrar-sesion (1).png"))); // NOI18N
        btnFinalizar.setText(" Finalizar sesión");
        btnFinalizar.addActionListener(this::btnFinalizarActionPerformed);
        jPanel2.add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 140, -1));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajeroautomatico/imagenes/email (1).png"))); // NOI18N
        jPanel2.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jPanel3.setBackground(new java.awt.Color(218, 241, 222));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 56, 50), 2, true));

        lblMensaje.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(0, 0, 0));
        lblMensaje.setText("Hemos enviado el comprobante ");

        lblMensaje1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblMensaje1.setForeground(new java.awt.Color(0, 0, 0));
        lblMensaje1.setText("de tu operación a:");

        lblCorreo.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(11, 43, 38));
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorreo.setText("[mail]");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblMensaje))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(lblMensaje1))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje1)
                .addGap(27, 27, 27)
                .addComponent(lblCorreo)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 260, 140));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 300, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnMenuFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuFocusGained

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaComprobante().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMensaje1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
