/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cajero.vista;

/**
 *
 * @author ymala
 */
public class PantallaBloqueada extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaBloqueada.class.getName());

    /**
     * Creates new form PantallaBloqueada
     */
    public PantallaBloqueada() {
        initComponents();
        this.setSize(709, 451);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblIcono = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        lblMensaje1 = new javax.swing.JLabel();
        lblInstruccion = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblContacto = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cajero Automatico");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(123, 2, 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 0, 0), 3, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajeroautomatico/imagenes/candado (1).png"))); // NOI18N
        jPanel2.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(11, 43, 38));
        lblTitulo.setText("por 3 intentos fallidos");
        jPanel2.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 240, -1));

        lblTitulo1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(11, 43, 38));
        lblTitulo1.setText("Tu cuenta ha sido bloqueada ");
        jPanel2.add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lblMensaje.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(0, 0, 0));
        lblMensaje.setText("Por tu seguridad, tu cuenta ha sido ");
        jPanel2.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        lblMensaje1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblMensaje1.setForeground(new java.awt.Color(0, 0, 0));
        lblMensaje1.setText("temporalmente bloqueada.");
        jPanel2.add(lblMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 30));

        lblInstruccion.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblInstruccion.setForeground(new java.awt.Color(0, 0, 0));
        lblInstruccion.setText("Contacta a tu banco para desbloquearla");
        jPanel2.add(lblInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jPanel3.setBackground(new java.awt.Color(239, 154, 154));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(248, 72, 72), 2, true));

        lblContacto.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblContacto.setForeground(new java.awt.Color(0, 0, 0));
        lblContacto.setText("Información de contacto:");

        lblTelefono.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefono.setText("📞 Teléfono: 809-123-4567 ");

        lblEmail.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText("📧 Email: soporte@bancodigital.com  ");

        lblHorario.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        lblHorario.setForeground(new java.awt.Color(0, 0, 0));
        lblHorario.setText("🕐 Horario: 24/7");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContacto)
                    .addComponent(lblTelefono)
                    .addComponent(lblEmail)
                    .addComponent(lblHorario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblContacto)
                .addGap(18, 18, 18)
                .addComponent(lblTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHorario)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 270, 120));

        btnVolver.setBackground(new java.awt.Color(229, 115, 115));
        btnVolver.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(123, 2, 2));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajeroautomatico/imagenes/flecha.png"))); // NOI18N
        btnVolver.setText(" Volver al incio");
        btnVolver.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnVolverFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnVolverFocusLost(evt);
            }
        });
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 140, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 310, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnVolverFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverFocusGained

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVolverFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnVolverFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaBloqueada().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblContacto;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMensaje1;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    // End of variables declaration//GEN-END:variables
}
