
package cajero.vista;

import cajero.bd.CuentaDAO;
import cajero.modelo.Cuenta;
import cajero.modelo.Transferencia;
import cajero.modelo.Usuario;
import java.awt.Color;


public class PantallaTransferencia extends javax.swing.JFrame {

    /**
     * Creates new form PantallaTransferencia
     */
    
    private Usuario usuarioSesion;
    
    public PantallaTransferencia(Usuario user) {
        initComponents();
        this.setSize(709, 451);
        this.pack();
        lblError.setVisible(true);
        this.usuarioSesion = user;
        setLocationRelativeTo(null);   
        
        txtCuentaDestino.setForeground(Color.GRAY);
        txtCuentaDestino.setText(" Ingresa el número de cuenta destino");

        txtCuentaDestino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtCuentaDestino.getText().equals(" Ingresa el número de cuenta destino")) {
                    txtCuentaDestino.setText("");
                    txtCuentaDestino.setForeground(Color.BLACK);
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtCuentaDestino.getText().isEmpty()) {
                    txtCuentaDestino.setForeground(Color.GRAY);
                    txtCuentaDestino.setText(" Ingresa el número de cuenta destino");
                }
            }
        });
        
        txtMonto.setForeground(Color.GRAY);
        txtMonto.setText(" Ingresa el monto");

        txtMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtMonto.getText().equals(" Ingresa el monto")) {
                    txtMonto.setText("");
                    txtMonto.setForeground(Color.BLACK);
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtMonto.getText().isEmpty()) {
                    txtMonto.setForeground(Color.GRAY);
                    txtMonto.setText(" Ingresa el monto");
                }
            }
        });
        
        mostrarSaldo(); // Llamamos a la función para mostrar el dinero
    }
    
    private void mostrarSaldo() {
        CuentaDAO dao = new CuentaDAO();
        double saldo = dao.obtenerSaldo(usuarioSesion.getId());

        // Formateamos el texto para que se vea profesional
        lblSaldo.setText("Saldo disponible: $ " + String.format("%.2f", saldo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCuentaDestino = new javax.swing.JLabel();
        txtCuentaDestino = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblSaldo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cajero Automatico");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(5, 31, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 182, 155), 3, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(11, 43, 38));
        lblTitulo.setText("Transferencia");
        jPanel2.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        lblCuentaDestino.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblCuentaDestino.setForeground(new java.awt.Color(0, 0, 0));
        lblCuentaDestino.setText("Número  de cuenta destino");
        jPanel2.add(lblCuentaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtCuentaDestino.setBackground(new java.awt.Color(204, 204, 204));
        txtCuentaDestino.setForeground(new java.awt.Color(153, 153, 153));
        txtCuentaDestino.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 182, 155), 1, true));
        txtCuentaDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuentaDestinoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCuentaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 250, 30));

        lblError.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblError.setForeground(new java.awt.Color(149, 18, 44));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 250, 40));

        btnConfirmar.setBackground(new java.awt.Color(142, 182, 155));
        btnConfirmar.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(11, 43, 38));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);
        jPanel2.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 100, 40));

        btnCancelar.setBackground(new java.awt.Color(179, 179, 179));
        btnCancelar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(43, 43, 43));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 90, 40));

        lblSaldo.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(22, 56, 50));
        lblSaldo.setText("Saldo disponible: [Monto]");
        jPanel2.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajeroautomatico/imagenes/transferencia grande.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        lblMonto.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(0, 0, 0));
        lblMonto.setText("Monto a transferir");
        jPanel2.add(lblMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtMonto.setBackground(new java.awt.Color(204, 204, 204));
        txtMonto.setForeground(new java.awt.Color(153, 153, 153));
        txtMonto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 182, 155), 1, true));
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });
        jPanel2.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 250, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 300, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Volver al menú principal
        MenuPrincipal menu = new MenuPrincipal(usuarioSesion);
        menu.setVisible(true);

        // Cerrar la pantalla de transferencia
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        String numeroDestino = txtCuentaDestino.getText();
        
        // "\\d{8}" significa: solo números y que sean exactamente 8
        if (!numeroDestino.matches("\\d{8}")) {
            lblError.setText("<html>El número de cuenta debe tener exactamente 8 dígitos numéricos.</html>");
            lblError.setVisible(true);
            return;
        }
        
        try {
        double monto = Double.parseDouble(txtMonto.getText());
        
        CuentaDAO cuentaDAO = new CuentaDAO();
        Cuenta cuentaDestino = cuentaDAO.buscarCuentaPorNumero(numeroDestino);
        
        Transferencia transferencia = new Transferencia(
            usuarioSesion.getCuenta().getId(),
            monto,
            cuentaDestino
        );      
       
        if (cuentaDestino == null) {
            lblError.setText("Cuenta destino no encontrada.");
            return;
        }

        if (cuentaDestino.getId() == usuarioSesion.getCuenta().getId()) {
            lblError.setText("No puede transferir a su propia cuenta.");
            return;
        }

        
        // Aquí se ejecuta la transferencia y se setea mensajeError si algo falla
        if (transferencia.ejecutar(usuarioSesion.getCuenta())) {
            lblError.setText("");
            double saldoActual = usuarioSesion.getCuenta().getSaldo();
            new PantallaConfirmacion(transferencia, usuarioSesion, saldoActual).setVisible(true);
            this.dispose();
        } else {
            lblError.setText(transferencia.getMensajeError());
        }
        
        
        /*boolean exito = transferencia.ejecutar(usuarioSesion.getCuenta());
        if (exito) {
            double saldoActual = usuarioSesion.getCuenta().getSaldo();
            new PantallaConfirmacion(transferencia, usuarioSesion, saldoActual).setVisible(true);
            this.dispose();
        } else {
            lblError.setText(transferencia.getMensajeError());
            return;
        }*/

    } catch (NumberFormatException e) {
        lblError.setText("Ingrese valores numéricos.");
    }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtCuentaDestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaDestinoKeyTyped
        char c = evt.getKeyChar();

        // Si no es dígito o ya hay 4 caracteres, se ignora
        if (!Character.isDigit(c) || txtCuentaDestino.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCuentaDestinoKeyTyped

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
        char c = evt.getKeyChar();

        // Si no es dígito o ya hay 4 caracteres, se ignora
        if (!Character.isDigit(c) || txtMonto.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMontoKeyTyped

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCuentaDestino;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCuentaDestino;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
